import Head from 'next/head'
import { ThumbUpIcon } from '@heroicons/react/solid'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="inset-0 absolute flex items-center justify-center">
        <h1 className="flex items-center text-2xl" data-test="top-page-title">
          Welcome to&nbsp;
          <a href="https://nextjs.org">Next.js!</a>
          <ThumbUpIcon className="w-8 ml-2" />
        </h1>
      </main>
    </div>
  )
}
