import Head from 'next/head'
import { ThumbUpIcon } from '@heroicons/react/solid'
import { Icon, Flex, Heading } from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        pos="absolute"
        top="0"
        left="0"
        right="0"
        bottom="0"
        justify="center"
        alignItems="center"
        height="100vh"
        fontSize="2xl"
        data-testid="top-page-title"
      >
        <Heading as="h1" >
          Welcome to&nbsp;
          <a href="https://nextjs.org">Next.js!</a>
          <Icon as={ThumbUpIcon} h={12} w={12} ml={1} pb={2} />
        </Heading>
      </Flex>
    </div>
  )
}
